###########################################
# Made by Carbrito (@cabritoing) in 2025. #
#                                         #
# Try `python vbsi.py ?` to see help.     #
###########################################

import sys, os, base64, re

def read_file(f):
    try: return open(f, 'r', encoding='utf-8').read()
    except: return False

def write_file(f, c):
    try:
        with open(f, 'w', encoding='utf-8') as w: w.write(c)
        return True
    except: return False

def error(msg): print(f"vbsi: error: {msg}"); sys.exit(1)
def success(msg): print(f"[ok] {msg}")

class Builder:
    class FileConfig:
        def __init__(self):
            self.filename = ''
            self.output_name = "out.vbs"
            self.dev_name = ''
            self.include_exes = False
            self.keep_comments = False

        def import_cfg(self, filename="build.cfg"):
            try:
                for l in read_file(filename).splitlines():
                    if "=" in l and not l.strip().startswith("#"):
                        k, v = [x.strip() for x in l.split("=", 1)]
                        v = v.strip('"').strip("'")
                        if v.lower() in ["true", "false"]: v = v.lower() == "true"
                        elif v.isdigit(): v = int(v)
                        if k in self.__dict__: self.__dict__[k] = v
                return True
            except: return False

    def __init__(self):
        self.cfg = Builder.FileConfig()
        self.embedded = {}

    def clean_comments(self, code):
        return "\n".join(l for l in code.splitlines() if not l.strip().startswith("'"))

    def parse_imports(self, code, base_dir):
        invalid = re.findall(r'^\s*import\s+[^\s"].*$', code, re.MULTILINE)
        if invalid: error("invalid import syntax (missing quotes)")

        def include(m):
            path = m.group(1).strip('"')
            full = os.path.join(base_dir, path)
            if not os.path.exists(full):
                error(f"import: file '{path}' not found")
            if path.lower().endswith('.vbs'):
                return f"\n' Imported: {path}\n" + read_file(full)
            elif path.lower().endswith('.exe'):
                if not self.cfg.include_exes:
                    return f"' skipped .exe import ({path})"
                data = base64.b64encode(open(full, 'rb').read()).decode()
                varname = os.path.basename(path).replace('.', '_')
                self.embedded[varname.lower()] = data
                return f"' Embedded EXE: {path}\nexe_{varname} = \"{data}\""
            else:
                error(f"unsupported import type: {path}")
        return re.sub(r'import\s+"([^"]+)"', include, code)

    def parse_execs(self, code):
        def repl(m):
            name = m.group(1).strip().strip('"').strip("'")
            flags_raw = (m.group(2) or "").strip()
            flags = [f.strip() for f in flags_raw.split(",") if f.strip()]
            for f in flags:
                if f not in ["NoWindow", "WaitEnd"]:
                    error(f"invalid flag '{f}' in exec()")
            flags_str = ",".join(flags)
            return f'ExecCmd("{name}", "{flags_str}")'
        return re.sub(r'exec\s*\(\s*([^,)\s][^,)]*)(?:\s*,\s*([^)]+))?\)', repl, code, flags=re.I)

    def parse_semicolons(self, code):
        out = []
        for l in code.splitlines():
            parts = [p.strip() for p in l.split(";") if p.strip()]
            out.extend(parts or [""])
        return "\n".join(out)

    def build(self):
        if not self.cfg.filename: error("no input file specified")
        code = read_file(self.cfg.filename)
        if not code: error(f"cannot read file '{self.cfg.filename}'")

        base_dir = os.path.dirname(self.cfg.filename) or "."
        code = self.parse_imports(code, base_dir)
        code = self.parse_execs(code)
        code = self.parse_semicolons(code)
        if not self.cfg.keep_comments: code = self.clean_comments(code)

        header = (
            "' ##############################################################\n"
            "' # This file was automatically generated by VBSI Builder.     #\n"
            "' # Do NOT modify this file directly.                         #\n"
            "' ##############################################################\n\n"
        )

        entry = "Call main\n\n" if "Call main" not in code.lower() else ""

        exe_block = ""
        if self.embedded:
            exe_block += "Set exeMap = CreateObject(\"Scripting.Dictionary\")\n"
            for n in self.embedded:
                exe_block += f"exeMap.Add LCase(\"{n}\"), exe_{n}\n"
            exe_block += "\nFunction Base64Decode(b64)\n"
            exe_block += "    Dim x,e:Set x=CreateObject(\"MSXML2.DOMDocument\"):Set e=x.createElement(\"b64\")\n"
            exe_block += "    e.dataType=\"bin.base64\":e.text=b64:Base64Decode=e.nodeTypedValue\nEnd Function\n\n"

        exec_func = (
            "Function ExecCmd(path, flags)\n"
            "    Dim s,fso,tmp,b64,nowin,wait,rc\n"
            "    Set s=CreateObject(\"WScript.Shell\")\n"
            "    nowin=(InStr(UCase(flags),\"NOWINDOW\")>0)\n"
            "    wait=(InStr(UCase(flags),\"WAITEND\")>0)\n"
            "    If IsObject(exeMap) Then\n"
            "        If exeMap.Exists(LCase(path)) Then\n"
            "            Set fso=CreateObject(\"Scripting.FileSystemObject\")\n"
            "            tmp=fso.GetSpecialFolder(2)&\"\\\"&path\n"
            "            b64=exeMap(LCase(path))\n"
            "            Dim st:Set st=CreateObject(\"ADODB.Stream\")\n"
            "            st.Type=1:st.Open:st.Write Base64Decode(b64)\n"
            "            If fso.FileExists(tmp) Then fso.DeleteFile tmp,True\n"
            "            st.SaveToFile tmp,2:st.Close\n"
            "            rc=s.Run(Chr(34)&tmp&Chr(34),IIf(nowin,0,1),wait)\n"
            "            fso.DeleteFile tmp,True\n"
            "            ExecCmd=rc:Exit Function\n"
            "        End If\n"
            "    End If\n"
            "    rc=s.Run(path,IIf(nowin,0,1),wait)\n"
            "    ExecCmd=rc\nEnd Function\n\n"
        )

        final = header + entry + exe_block + exec_func + code
        if not write_file(self.cfg.output_name, final):
            error(f"failed to write {self.cfg.output_name}")
        success(f"build complete → {self.cfg.output_name}")

builder = Builder()

def parse_args(args):
    if len(args) < 2:
        error("no input files\nTry `python vbsi.py ?` for help.")
    i = 1
    while i < len(args):
        a = args[i]
        match a:
            case "?":
                print("# VBSI HELP MENU\n\n"
                      "  -e              Generate example file\n"
                      "  -cfg [file]     Load build.cfg\n"
                      "  -o [file]       Output filename\n"
                      "  -d [string]     Developer name\n"
                      "  -ie [bool]      Include EXEs\n"
                      "  -kc [bool]      Keep comments")
                sys.exit(0)
            case "-ie" | "-kc" | "-cfg" | "-o" | "-d":
                if i+1 >= len(args) or args[i+1].startswith("-"):
                    error(f"option '{a}' requires a value")
                v = args[i+1]
                match a:
                    case "-ie": builder.cfg.include_exes = v.lower() in ["1","true"]
                    case "-kc": builder.cfg.keep_comments = v.lower() in ["1","true"]
                    case "-cfg":
                        if not builder.cfg.import_cfg(v): error(f"failed to import config '{v}'")
                    case "-o": builder.cfg.output_name = v
                    case "-d": builder.cfg.dev_name = v
                i += 1
            case "-e":
                write_file("VBSI_examples.vbs", 
"""' -------------------------------
' VBSI EXTENSIONS EXAMPLE
' -------------------------------
import "utilities.vbs"
import "myexe.exe"
import "boolgenerator.exe"

Function Main()
    PrintMessage("Hello world!")
    zero = exec("boolgenerator.exe", NoWindow, WaitEnd)
    exec("myexe.exe", NoWindow, WaitEnd)
End Function
""")
                success("example 'VBSI_examples.vbs' created.")
                sys.exit(0)
            case _: builder.cfg.filename = a
        i += 1

if __name__ == "__main__":
    parse_args(sys.argv)
    builder.build()